- name: Finance
  head-widgets:
    - type: markets
      hide-header: true
      markets:
        - symbol: SPY
          name: S&P 500
        - symbol: BTC-USD
          name: Bitcoin
        - symbol: NVDA
          name: NVIDIA
        - symbol: AAPL
          name: Apple
        - symbol: MSFT
          name: Microsoft

  columns:
    - size: full
      widgets:
        - type: videos
          channels:
            - UCODr9HUJ90xtWD-0Xoz4vPw # Hamish Hodder
