services:
  any-sync-node-1:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
      args:
        REPO_DIR: repos/any-sync-node/
  any-sync-node-2:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
      args:
        REPO_DIR: repos/any-sync-node/
  any-sync-node-3:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
      args:
        REPO_DIR: repos/any-sync-node/
